### ISSUE TITLE
Viewing Issues

### ISSUE THREAD

**Issue by ZachReis** [CssFly/SpeedPaint#1]
Hey, 
I've been using SpeedPaint at different locations and for some reason they won't work in one. Can you help me out by telling me why I can view and edit my image in one location but not in the other? 
Thanks!
Zach Reis
![logo1](https://cloud.githubusercontent.com/assets/28161350/25544287/d367c1a8-2c27-11e7-95ef-a9c653071101.png)

**Comment by CssFly** [comment]
If you use multi user version of Speedpaint, it may be that the connection to the server can not be established. Mostly this happens in private networks where only port 80 is allowed.

**Comment by ZachReis** [comment]
Ok. But I was using the normal Speedpaint Version. Mainly I am trying to view my speedpaint in action, but when I load it from the gallery, it just takes me to the edit screen, loads, and my picture flashes on the workspace for half a second and disappears. I want to be able to view and edit it.

**Comment by CssFly** [comment]
Now I could reproduce and fix it. Thanks for reporting.

**Comment by ZachReis** [comment]
Yes. If you are fixing it, thanks. This was another problem I faced when trying to view/edit it. Not only did the picture not load, some tools were missing as well (such as the curve tool and a different layout).

**Comment by ZachReis** [comment]
Just now I tested it, There are now more problems. The two layers have merged into one and the play button won't play the drawing animation. Other than that, it's the same.

**Comment by CssFly** [comment]
Yeah there are two different versions of the program. One is realized in Flash and one in HTML5. The Flash version has much more features and different layout. If Flash is not available in the browser, it will fall back to the HTML5 version with limited features.
